### ISSUE TITLE
HP Warranty API

### ISSUE THREAD

**Issue by pablitobin** [InfotelGLPI/manufacturersimports#118]
Hi Team!
Is there any way to get information for HP devices? I see that API is not working.

**Comment by maxplettenberg** [comment]
Due to reverse engineering there was a valid warranty API detected. 

[https://www.cyberdrain.com/automating-with-powershell-getting-device-warranty-information/](url)
[https://github.com/KelvinTegelaar/PowerShellWarrantyReports/blob/master/private/Get-HPWarranty.ps1](url)

https://warrantyapiproxy.azurewebsites.net/api/HP?serial=

I could not update the HP template.
