### ISSUE TITLE
Some service tag can't be imported

### ISSUE THREAD

**Issue by Alwaysin** [InfotelGLPI/manufacturersimports#67]
* Version of the plugin : 2.1.2

* Version of your GLPI : 9.3.0

* Steps to reproduce (which actions have you made) : looking for computers not yet imported, then trying to import

* Expected result : warranty details to be found

* Actual result : some computers are imported, some others are not (and not displayed on the result page)

When searching again for computers not imported, they appear with a red text message sayng "Problème lors de l'importation" (problem occured while importing). What could it be?
It looks I don't have any logs produced in files/_log/ related to this.

Example of a service tag not working: https://api.dell.com/support/assetinfo/v4/getassetwarranty/1ZMGZ42?apikey=xxx

**Comment by amma35** [comment]
It works on my side with the serial number: 
![dell](https://user-images.githubusercontent.com/15138371/45145668-84d29d80-b1c1-11e8-8fcc-16e6221b76be.png)

If you have already imported the machine and when viewing the machines you have in the "Problem during the importation" status, you must reset the import otherwise it will not work.

![dell1](https://user-images.githubusercontent.com/15138371/45145717-9d42b800-b1c1-11e8-8a1e-6e7177caa9ac.png)

**Comment by Alwaysin** [comment]
@amma35 Thank you! Didn't pay attention at the reset in the dropdown. It works perfectly!
