### ISSUE TITLE
Multiples Dell Warranty

### ISSUE THREAD

**Issue by duylong** [InfotelGLPI/manufacturersimports#90]
Hi,

I tested the new version with Dell APIv5 and I have a problem.

Indeed, I have several maintenance contracts attached to equipment. And each time I reset and import, I have different end dates. I have the impression that the contracts are retrieved in any order and that the plugin retrieves only the last value.

Can you modify the behavior to recover all the elements, sort by end date and get only the most recent?

Best regards,

**Comment by adul3** [comment]
Hi !

Similar problem for me ; as some of my machines are imported with the wrong expiration date and warranty description :'(

Regards.

**Comment by enannos** [comment]
Hi,

how did you get any results? 
My installation and from many others doesn't seem to work.
Can you please tell us all the steps performed after the installation of the plugin?

Nobody from the developers seems to reply to the questions..
Thanks

**Comment by fggroupemarck** [comment]
> Hi,
> 
> how did you get any results?
> My installation and from many others doesn't seem to work.
> Can you please tell us all the steps performed after the installation of the plugin?
> 
> Nobody from the developers seems to reply to the questions..
> Thanks

My configuration was setup by Infotel Company and work very well but since few week Plugins get wrong information from Dell ( only first line )

**Comment by servain-m** [comment]
This issue seems to be more complexe than getting the most recent end warranty date. I have three different cases where the warranty start date and the overall duration are not taken into account.

- Case 1 (Dell Latitude 5400) : A first "ProSupport Flex for Client" warranty from expedition date +1 day and for 12 months, followed by a second "ProSupport Flex for Client" warranty from the first warranty end date + 1 day and for 36 months.
![Dell Latitude 5400](https://user-images.githubusercontent.com/61057899/87687209-c224f080-c785-11ea-9f77-186edecc7517.png)
The result is randomly the first or the second one but it should be the overall of the two ones : "ProSupport Flex for Client" from expedition date +1 day and for 48 months.

- Case 2 (Dell Latitude 5485) : A "CAR" warranty from expedition date +1 day and for 12 month, and a "ProSupport Flex for Client" warranty from the same date and for 36 months.
![Dell Latitude 5495](https://user-images.githubusercontent.com/61057899/87688287-17adcd00-c787-11ea-8732-46f6b2586e52.png)
The result can be the first one (with 12 months duration) but it should be only the second one.
Warning: the "battery exchange service" may in some cases exceed the "Prosupport Flex for Client" warranty (if it lasts only 12 months for example). But it is the values of the "Prosupport Flex for Client" warranty that must be saved.

- Case 3 (Dell Precision 3541) : This case is similar to the previous one where only the "ProSupport Flex for Client" warranty should be retained (with a duration of 72 months instead of 12).
![Dell Precision 3541 4QV0Z33](https://user-images.githubusercontent.com/61057899/87688739-a7ec1200-c787-11ea-83fc-1976c2cfc80e.png)

**Comment by adul3** [comment]
Hi.

Here's how i've been configuring the manufacturer in the plugin.

```
Name                      : DELL
Child entities            : Yes
Manufacturer              : Dell Inc.
Manufacturer web address  : https://www.dell.com/support/home/product-support/servicetag/
Access token API address  : https://apigtwb2c.us.dell.com/auth/oauth/v2/token
Warranty API address      : https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=
Default supplier attached : Dell API
Client id                 : my_id
Client secret             : my_secret
Add a comment line        : Yes
```

**Comment by enannos** [comment]
> 
> 
> Hi.
> 
> Here's how i've been configuring the manufacturer in the plugin.
> 
> ```
> Name                      : DELL
> Child entities            : Yes
> Manufacturer              : Dell Inc.
> Manufacturer web address  : https://www.dell.com/support/home/product-support/servicetag/
> Access token API address  : https://apigtwb2c.us.dell.com/auth/oauth/v2/token
> Warranty API address      : https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=
> Default supplier attached : Dell API
> Client id                 : my_id
> Client secret             : my_secret
> Add a comment line        : Yes
> ```

And does it work? 
We have more than 400 computers and I get the error *** PHP Notice(8): Undefined index: fromwarranty
https://github.com/InfotelGLPI/manufacturersimports/issues/88

**Comment by jeremy160189** [comment]
Hello, we have the same issue, randomly some warrantly are incorrectly imported (it doesn't take the last warrantly).
Do you have any idea, correction to this problem ?

**Comment by ellmout** [comment]
Hello,
After debugging Dell API, i discovered that they return warranty in a random order, one time in first place, second time, last place, etc...
So i updated my dell.class.php like this :
`   /**
    * @see PluginManufacturersimportsManufacturer::getExpirationDate()
    */
   function getExpirationDate($contents) {
      $info = json_decode($contents, true);
      // v5
      // when several dates are available, will take the last one
      $max_date = false;
      foreach ($info[0]['entitlements'] as $d) {
              $date = new \DateTime($d['endDate']);
              if ($max_date == false || $date > $max_date) {
                 $max_date = $date;
              }
      }

      if ($max_date) {
         return $max_date->format('c');
      }

      return false;
   }

   /**
    * @see PluginManufacturersimportsManufacturer::getWarrantyInfo()
    */
   function getWarrantyInfo($contents) {
      $info = json_decode($contents, true);
      // v5
      // when several warranties are available, will take the last one
      $max_date	= false;
      $i = false;
      foreach ($info[0]['entitlements'] as $k => $d) {
              $date = new \DateTime($d['endDate']);
              if ($max_date == false || $date > $max_date) {
                 $max_date = $date;
                 $i = $k;
              }
      }

      if ($max_date && $i) {
         return	$info[0]['entitlements'][$i]['serviceLevelDescription'];
      }

      return false;
   }`

the function will now try to find the max warranty date, instead of taking the last one.

**Comment by rlamotte-png** [comment]
> Hello,
> After debugging Dell API, i discovered that they return warranty in a random order, one time in first place, second time, last place, etc...
> So i updated my dell.class.php like this :
> 
> ```
>     /**
>     * @see PluginManufacturersimportsManufacturer::getExpirationDate()
>     */
>    function getExpirationDate($contents) {
>       $info = json_decode($contents, true);
>       // v5
>       // when several dates are available, will take the last one
>       $max_date = false;
>       foreach ($info[0]['entitlements'] as $d) {
>               $date = new \DateTime($d['endDate']);
>               if ($max_date == false || $date > $max_date) {
>                  $max_date = $date;
>               }
>       }
> 
>       if ($max_date) {
>          return $max_date->format('c');
>       }
> 
>       return false;
>    }
> 
>    /**
>     * @see PluginManufacturersimportsManufacturer::getWarrantyInfo()
>     */
>    function getWarrantyInfo($contents) {
>       $info = json_decode($contents, true);
>       // v5
>       // when several warranties are available, will take the last one
>       $max_date	= false;
>       $i = false;
>       foreach ($info[0]['entitlements'] as $k => $d) {
>               $date = new \DateTime($d['endDate']);
>               if ($max_date == false || $date > $max_date) {
>                  $max_date = $date;
>                  $i = $k;
>               }
>       }
> 
>       if ($max_date && $i) {
>          return	$info[0]['entitlements'][$i]['serviceLevelDescription'];
>       }
> 
>       return false;
>    }
> ```
> 
> the function will now try to find the max warranty date, instead of taking the last one.

Thank you for your modification I installed it manually is working fine

**Comment by enannos** [comment]
> 
> 
> Hello,
> After debugging Dell API, i discovered that they return warranty in a random order, one time in first place, second time, last place, etc...
> So i updated my dell.class.php like this :
> 
> ```
>     /**
>     * @see PluginManufacturersimportsManufacturer::getExpirationDate()
>     */
>    function getExpirationDate($contents) {
>       $info = json_decode($contents, true);
>       // v5
>       // when several dates are available, will take the last one
>       $max_date = false;
>       foreach ($info[0]['entitlements'] as $d) {
>               $date = new \DateTime($d['endDate']);
>               if ($max_date == false || $date > $max_date) {
>                  $max_date = $date;
>               }
>       }
> 
>       if ($max_date) {
>          return $max_date->format('c');
>       }
> 
>       return false;
>    }
> 
>    /**
>     * @see PluginManufacturersimportsManufacturer::getWarrantyInfo()
>     */
>    function getWarrantyInfo($contents) {
>       $info = json_decode($contents, true);
>       // v5
>       // when several warranties are available, will take the last one
>       $max_date	= false;
>       $i = false;
>       foreach ($info[0]['entitlements'] as $k => $d) {
>               $date = new \DateTime($d['endDate']);
>               if ($max_date == false || $date > $max_date) {
>                  $max_date = $date;
>                  $i = $k;
>               }
>       }
> 
>       if ($max_date && $i) {
>          return	$info[0]['entitlements'][$i]['serviceLevelDescription'];
>       }
> 
>       return false;
>    }
> ```
> 
> the function will now try to find the max warranty date, instead of taking the last one.

After you modification, I am getting the following errors:

glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/glpi/plugins/manufacturersimports/inc/dell.class.php at line 164
  Backtrace :
  ...nufacturersimports/inc/postimport.class.php:298 PluginManufacturersimportsDell->getWarrantyInfo()
  ...nufacturersimports/inc/postimport.class.php:526 PluginManufacturersimportsPostImport::importWarrantyInfo()
  ...s/manufacturersimports/inc/import.class.php:109 PluginManufacturersimportsPostImport::saveImport()
  ...ins/manufacturersimports/inc/dell.class.php:207 PluginManufacturersimportsImport::importCron()
  inc/crontask.class.php:847                         PluginManufacturersimportsDell::cronDataRecoveryDELL()
  front/crontask.form.php:49                         CronTask::launch()

**Comment by fralla2** [comment]
"Dell Digital Delivery" should be discarded as a warranty information because it messes-up the dates...

See for example this asset : 
https://www.dell.com/support/home/en-ca/product-support/servicetag/0-eFc3RkFLekZxYnBuMXlHbDBGbXpnUT090/overview#

![image](https://user-images.githubusercontent.com/38400135/105495233-ecea8700-5c89-11eb-862c-9c2a64e45107.png)

It should have took the older date as the beginning date of the warranty (the one in green), not accounting for "Dell Digital Delivery" whom should be discarded to begin with, and the newest date for the end of warranty (because the total warranty is the combination of a few support levels contracts over the years)...

In all cases, it should discard the digital delivery as it's only covering for how long Dell would be providing downloads for drivers and softwares for this machine and not related to the hardware itself...

Also, a really big thanks for your good work, it's really appreciated.

Francois
